// ? FETCH MOVIES SECTION 
export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';
// ? END OF FETCH MOVIES SECTION
// ? VIEW MOVIES SECTION Top rated movie
export const VIEW_MOVIES_REQUEST = 'VIEW_MOVIES_REQUEST';
export const VIEW_MOVIES_SUCCESS = 'VIEW_MOVIES_SUCCESS';
export const VIEW_MOVIES_FAILURE = 'VIEW_MOVIES_FAILURE';
// ? END OF VIEW MOVIES SECTION

// ! DELETE MOVIE SECTION
export const DELETE_MOVIE_REQUEST = 'DELETE_MOVIE_REQUEST';
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';
export const DELETE_MOVIE_FAILURE = 'DELETE_MOVIE_FAILURE';
// ! END OF DELETE MOVIE SECTION

// * ADD MOVIE SECTION
export const ADD_MOVIE_REQUEST = 'ADD_MOVIE_REQUEST';
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS';
export const ADD_MOVIE_FAILURE = 'ADD_MOVIE_FAILURE';
// * END OF ADD MOVIE SECTION


// * search movie section

export const SEARCH_MOVIE_REQUEST = 'SEARCH_MOVIE_REQUEST';


// * end of search movie section

// * update movie section

export const UPDATE_MOVIE_REQUEST = 'UPDATE_MOVIE_REQUEST';
export const UPDATE_MOVIE_SUCCESS = 'UPDATE_MOVIE_SUCCESS';
export const UPDATE_MOVIE_FAILURE = 'UPDATE_MOVIE_FAILURE';


// latest movie section

export const LATEST_MOVIE_REQUEST = 'LATEST_MOVIE_REQUEST';
export const LATEST_MOVIE_SUCCESS = 'LATEST_MOVIE_SUCCESS';
export const LATEST_MOVIE_FAILURE = 'LATEST_MOVIE_FAILURE';
